name: mindsync
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_messaging: ^14.7.11
  firebase_analytics: ^10.8.4

  lottie: ^1.2.2
  flutter_riverpod: ^2.4.9
  # shared_preferences: ^2.0.9
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
    - assets/images/angry_face.png
    - assets/images/sad_face.png
    - assets/images/med_face.png
    - assets/images/happy_face.png
    - assets/images/laugh_face.png
    - assets/images/meditation.png
    - assets/images/breathing.png
    - assets/images/articles.png
    - assets/images/affirmations.png
    - assets/images/quotes.png
    - assets/images/journal.png
    - assets/images/mental_health.png
