name: mindsync
description: "MindSync: Your Mental Health Wellness Companion"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: 5.6.4 
  lottie: ^3.2.0
  flutter_riverpod: ^2.4.9
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  firebase_core_web: ^2.21.0
  table_calendar: ^3.0.0
  fl_chart: ^0.70.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
    - assets/.env